import { Jacques_Francois_Shadow, Raleway } from 'next/font/google';

import '@/app/_styles/globals.css';
import Header from '@/app/_components/Header';

const jacques = Jacques_Francois_Shadow({ subsets: ['latin'], weight: '400' });
const montserrat = Raleway({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata = {
  title: "Sephine's Portfolio",
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${montserrat.className} text-primary-800 tracking-wide`}
      >
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
