import Image from "next/image";
import heroImg from "@/public/hero.png";
import TextLoop from "@/app/_ui/TextLoop";
import ArrowDown from "@/app/_ui/ArrowDown";

export default function Hero() {
  return (
    <section className="flex h-[650px] items-center justify-center bg-accent-50">
      <div className="relative m-5 flex h-2/3 w-full max-w-7xl justify-between pt-8">
        <h1 className="absolute top-[16%] text-4xl font-light tracking-wide">
          Hey there, my name is&nbsp;
          <span className="font-bold text-primary-600">Soohyun Kang</span>,
        </h1>
        <TextLoop />
        <div className="absolute top-[70%] max-w-[40rem] text-xl font-normal">
          I&apos;m a Frontend Developer, passionate about web development and
          creating innovative solutions for problems. I enjoy learning new
          technologies everyday. I&apos;m currently based on Glendale, CA 🏡.
        </div>
        <Image
          src={heroImg}
          width={350}
          height={350}
          placeholder="blur"
          className="absolute right-0 rounded-3xl"
          alt="Pink desk setup illustration"
          style={{ width: "auto", height: "auto" }}
        />
        <span className="absolute bottom-[3%] right-[2%] text-sm italic text-primary-300">
          Illustration generated by Canva AI Art Generator
        </span>
      </div>
      <ArrowDown />
    </section>
  );
}
