import Image from "next/image";
import heroImg from "@/public/hero.png";
import TextLoop from "../_ui/TextLoop";

export default function Hero() {
  return (
    <section className="flex h-[550px] items-center justify-center bg-accent-50">
      <div className="relative m-5 flex h-2/3 w-full max-w-7xl justify-between">
        <h1 className="absolute top-[4%] text-3xl font-light tracking-wide">
          Hey there, my name is Soohyun Kang,
        </h1>
        <TextLoop />
        <div className="absolute top-[65%] max-w-xl text-xl font-normal">
          I'm a Frontend Developer based in Glendale, CA. I'm passionate about
          web development and creating innovative solutions for problems. I
          enjoy learning new technologies everyday.
        </div>
        <Image
          src={heroImg}
          width={350}
          height={350}
          placeholder="blur"
          className="absolute right-0 rounded-3xl"
          alt="Pink desk setup illustration"
          style={{ width: "auto", height: "auto" }}
        />
        <span className="absolute bottom-[-4%] right-[2%] text-sm italic text-primary-300">
          Illustration generated by Canva AI Art Generator
        </span>
      </div>
    </section>
  );
}
