import Image from "next/image";
import heroImg from "@/public/hero.png";
import TextLoop from "@/app/_ui/TextLoop";
import ArrowDown from "@/app/_ui/ArrowDown";
import Link from "next/link";
import { SiGithub, SiLinkedin, SiReaddotcv } from "react-icons/si";

export default function Hero() {
  return (
    <section className="flex h-[700px] flex-col bg-accent-50 pt-[3%]">
      <div className="relative m-10 mx-auto flex h-full w-full max-w-7xl justify-between pt-8">
        <h1 className="absolute top-[15%] text-4xl font-light tracking-wide">
          Hey there, my name is&nbsp;
          <span className="font-bold text-primary-600">Soohyun Kang</span>,
        </h1>
        <TextLoop />
        <div className="absolute top-[55%] max-w-[40rem] text-xl font-normal">
          I&apos;m a Frontend Developer, passionate about web development and
          creating innovative solutions for problems. I enjoy learning new
          technologies everyday. I&apos;m currently based on Glendale, CA 🏡.
        </div>
        <Image
          src={heroImg}
          width={350}
          height={350}
          placeholder="blur"
          className="absolute right-0 mt-10 rounded-3xl shadow-lg"
          alt="Pink desk setup illustration"
          style={{ width: "auto", height: "auto" }}
        />
        <span className="absolute bottom-[15%] right-[2%] text-sm italic text-primary-300">
          Illustration generated by Canva AI Art Generator
        </span>

        <div className="mb-20 flex gap-4 self-end text-2xl text-primary-700">
          <Link
            href="https://github.com/sephinek"
            target="_blank"
            className="transition-all duration-200 hover:scale-105 hover:text-accent-200"
          >
            <SiGithub />
          </Link>
          <Link
            href="https://www.linkedin.com/in/soo-hyun-kang/"
            target="_blank"
            className="transition-all duration-200 hover:scale-105 hover:text-accent-200"
          >
            <SiLinkedin />
          </Link>
          <Link
            href="https://github.com/sephinek"
            target="_blank"
            className="transition-all duration-200 hover:scale-105 hover:text-accent-200"
          >
            <SiReaddotcv />
          </Link>
        </div>
      </div>
      <ArrowDown />
    </section>
  );
}
